server:
  port: 8301
spring:
  application:
           name: borrow-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 临时实例
        ephemeral: false
        cluster-name: Chengdu
        namespace: c5a5ab01-cf4f-4a94-9a39-ac3773fa8b54
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: localhost:8858
      web-context-unify: false
      block-page: /blocked
# 使用feign
feign:
  sentinel:
    enabled: true
